-- solov2-qd9 - Add a per-node `exported` visibility flag so graph tools
-- (eng_find_symbol / eng_get_node / eng_get_file_nodes) can surface whether a
-- symbol is exported instead of always returning null.
--
-- The parser sets domain.Node.Exported (e.g. Go: first rune uppercase); the
-- Promoter threads it onto each inserted row. Stored as INTEGER 0/1.
--
-- Forward-only: existing rows get NULL, which the read path maps back to a nil
-- *bool ("unknown") - the same representation as a node whose language has no
-- export concept.
ALTER TABLE nodes ADD COLUMN exported INTEGER;
