// SPDX-FileCopyrightText: 2026 Jeff Rose
// SPDX-License-Identifier: AGPL-3.0-only

// Command docgen generates derived Markdown reference pages for the manual
// from the live source, so they cannot drift from the code. `make docs-gen`
// runs it and CI fails if a committed page is stale.
// Subcommands:
//
//	docgen config <out.md> env-var reference, AST-extracted from
//	                         internal/platform/config (every os.Getenv("VESKA_*"))
//
// The CLI reference is generated separately by `veska gendocs` (it needs the
// in-process cobra command tree); the MCP tools reference is generated from the
// daemon's tools/list. See the Makefile docs-gen target.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	if len(os.Args) < 3 {
		fmt.Fprintln(os.Stderr, "usage: docgen config <out.md>")
		os.Exit(2)
	}
	switch os.Args[1] {
	case "config":
		if err := genConfig(os.Args[2]); err != nil {
			fmt.Fprintln(os.Stderr, "docgen config:", err)
			os.Exit(1)
		}
	default:
		fmt.Fprintln(os.Stderr, "docgen: unknown subcommand", os.Args[1])
		os.Exit(2)
	}
}

// genConfig walks internal/platform/config, collects every VESKA_* env var name
// referenced via os.Getenv, and writes a Markdown table to out.
func genConfig(out string) error {
	const pkgDir = "internal/platform/config"
	vars, err := collectEnvVars(pkgDir)
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("# Configuration reference\n\n")
	b.WriteString("<!-- GENERATED by `make docs-gen` (tools/docgen). DO NOT EDIT BY HAND. -->\n\n")
	b.WriteString("Veska's state lives under `~/.veska/` (override with `VESKA_HOME`). ")
	b.WriteString("Configuration is one TOML file (`~/.veska/config.toml`) plus the ")
	b.WriteString("environment variables below. Env vars override the matching TOML key.\n\n")
	b.WriteString("!!! note \"TOML keys and semantics\"\n")
	b.WriteString("    This page lists the environment variables, extracted from the\n")
	b.WriteString("    `internal/platform/config` source so the list stays complete. For the\n")
	b.WriteString("    full TOML schema, defaults, and which keys the daemon reads today, see\n")
	b.WriteString("    the canonical [Configuration Surface](https://github.com/whiskeyjimbo/veska/blob/main/docs/operations/CONFIG-SURFACE.md) doc.\n\n")
	b.WriteString("## Environment variables\n\n")
	b.WriteString("| Variable | Purpose |\n|---|---|\n")
	for _, v := range vars {
		fmt.Fprintf(&b, "| `%s` | %s |\n", v, envPurpose[v])
	}
	b.WriteString("\nA new `VESKA_*` env var that lands in the config source without a row ")
	b.WriteString("here makes `make docs-gen` regenerate this page; CI then fails the ")
	b.WriteString("staleness check until the page is committed.\n")

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}
	return os.WriteFile(out, []byte(b.String()), 0o644)
}

// envPurpose holds the one-line description for known env vars. Variables found
// in source but missing here render with a TODO marker so the gap is visible in
// the diff (and therefore in review) rather than silently blank.
var envPurpose = map[string]string{
	"VESKA_HOME":                 "Data root. All of Veska's state lives here (default `~/.veska`).",
	"VESKA_CONFIG":               "Explicit path to the TOML config file (overrides the `VESKA_HOME`-derived default).",
	"VESKA_CACHE_HOME":           "Cache root override (else `XDG_CACHE_HOME`, else a default under `~/.cache`).",
	"VESKA_CACHE_DECLINED_TTL":   "How long a declined cache entry stays suppressed.",
	"VESKA_CACHE_MAX_BYTES":      "Cache size ceiling in bytes (0 = unbounded).",
	"VESKA_CACHE_MAX_EPHEMERALS": "Max number of ephemeral cache entries retained.",
	"VESKA_OLLAMA_URL":           "Ollama base URL for the optional LLM review pipeline (default `http://localhost:11434`).",
	"VESKA_EMBED_MODEL":          "Embedding model name (default `nomic-embed-text`; only relevant when forcing an Ollama embedder).",
	"VESKA_VECTOR_BACKEND":       "Vector store backend: `memory` (default) or `usearch`.",
	"VESKA_DEBUG":                "Enable debug logging when set to a non-empty, non-`0` value.",
	"VESKA_OTLP_ENDPOINT":        "OTLP endpoint for tracing export (required when tracing is enabled).",
	"VESKA_HUB_THRESHOLD":        "Blast-radius hub-degree threshold (integer).",
	"VESKA_AUTOLINK_THRESHOLD":   "Autolink similarity threshold (float).",
	"VESKA_AUTOLINK_TOPK":        "Autolink candidate count (integer).",
}

func collectEnvVars(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	fset := token.NewFileSet()
	seen := map[string]bool{}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, 0)
		if err != nil {
			return nil, err
		}
		ast.Inspect(file, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok || sel.Sel.Name != "Getenv" {
				return true
			}
			if pkgIdent, ok := sel.X.(*ast.Ident); !ok || pkgIdent.Name != "os" {
				return true
			}
			if len(call.Args) != 1 {
				return true
			}
			lit, ok := call.Args[0].(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				return true
			}
			envName := strings.Trim(lit.Value, `"`)
			if strings.HasPrefix(envName, "VESKA_") {
				seen[envName] = true
			}
			return true
		})
	}

	out := make([]string, 0, len(seen))
	for k := range seen {
		if envPurpose[k] == "" {
			envPurpose[k] = "TODO: document this variable."
		}
		out = append(out, k)
	}
	sort.Strings(out)
	return out, nil
}
