//go:build docsgen

package daemon

// Generator for the manual's MCP tools reference
// ( gated behind the `docsgen` build tag so
// it stays OUT of the default `go test` / `make all` path. `make docs-gen` runs
// it; CI's docs-check fails if the committed page drifts.
// It reuses the test harness, which calls the production registerMCPTools - so
// the rendered catalog is exactly the surface the daemon publishes over
// tools/list, with no per-tool maintenance here. Adding or changing a tool
// flows through automatically.
//	go test -tags "sqlite_fts5 docsgen" -run TestGenerateMCPToolsDoc \
//	  /internal/cli/daemon/ -count=1
// Output path comes from MCP_DOCS_OUT (default
// resolved relative to the repo root - three levels up from this package).

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

func TestGenerateMCPToolsDoc(t *testing.T) {
	out := os.Getenv("MCP_DOCS_OUT")
	if out == "" {
		out = filepath.Join("..", "..", "..", "docs", "manual", "reference", "mcp-tools.md")
	}

	// Plain newHarness mirrors production registerMCPTools exactly (the 3 parked
	// task tools are intentionally not served, so they stay out of the manual).
	h := newHarness(t)

	var b bytes.Buffer
	b.WriteString("# MCP tools reference\n\n")
	b.WriteString("<!-- GENERATED by `make docs-gen` (TestGenerateMCPToolsDoc). DO NOT EDIT BY HAND. -->\n\n")
	b.WriteString("Every tool the daemon publishes over MCP (`tools/list`), with its input ")
	b.WriteString("schema. Your editor discovers these automatically once it's connected ")
	b.WriteString("(see [Connecting your editor](../guides/editor-setup.md)); this page is ")
	b.WriteString("the human-readable catalog.\n\n")

	tools := h.Registry().Tools()
	fmt.Fprintf(&b, "%d tools.\n", len(tools))

	for _, spec := range tools {
		fmt.Fprintf(&b, "\n## `%s`\n\n", spec.Name)
		if spec.Description != "" {
			fmt.Fprintf(&b, "%s\n\n", spec.Description)
		}
		if spec.IncludesStaging {
			b.WriteString("_Reads through the staging overlay (reflects uncommitted edits)._\n\n")
		}
		if len(spec.InputSchema) > 0 {
			b.WriteString("**Input schema:**\n\n```json\n")
			b.WriteString(prettyJSON(t, spec.InputSchema))
			b.WriteString("\n```\n\n")
		} else {
			b.WriteString("_No input parameters._\n\n")
		}
	}

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(out), err)
	}
	if err := os.WriteFile(out, b.Bytes(), 0o644); err != nil {
		t.Fatalf("write %s: %v", out, err)
	}
	t.Logf("wrote %s (%d tools)", out, len(tools))
}

// prettyJSON re-indents a raw JSON schema for readable display. On malformed
// input (which the registry rejects at Register-time anyway) it falls back to
// the raw bytes rather than failing the generator.
func prettyJSON(t *testing.T, raw json.RawMessage) string {
	t.Helper()
	var indented bytes.Buffer
	if err := json.Indent(&indented, raw, "", "  "); err != nil {
		return string(raw)
	}
	return indented.String()
}
