// SPDX-License-Identifier: AGPL-3.0-only

package mcp

// This file provides shared user-facing descriptions for MCP tools and CLI commands to prevent documentation drift.
// Constants are split into full descriptions (where MCP and CLI parameters map 1:1) and invariant fragments
// (where the MCP surface accepts more inputs than the CLI command).

const DescCallChain = "Walk CALLS edges from a symbol. Use this - not search - when the question is 'what does this reach' (direction=out, default) or 'what calls this' (direction=in). Surfaces cross_repo_edges into other registered repos so library-symbol callers in a multi-repo workspace are visible without separate queries. Pass node_id (exact) or symbol (resolved via eng_find_symbol; ambiguity is rejected). NOTE: empty edges on a function/method seed carry one of two degraded_reasons hints: 'chained_selectors_unresolved' (parser limit - chained selector call sites like rootCmd.AddCommand(...).Execute() or s.field.M() are not yet modeled) or 'external_callees_only' (index boundary - callees are stdlib or unregistered modules, NOT a parser bug). Fall back to eng_get_blast_radius, eng_search_semantic, or eng_find_symbol."

const DescBlastRadius = "Compute the blast radius (callers/callees/both) - 'if I change this, what breaks?' or 'what does this transitively reach?'. Use BEFORE editing an exported symbol, when scoping a refactor, or for PR review. Best for wide / cross-file / cross-repo impact; if a single obvious grep string would find the callers, grep is cheaper. Walks cross_repo_edges in both directions so a library symbol's consumers in workspace repos are surfaced. The 'seed' param selects what to blast: seed=symbol (default) fans out from node_id/symbol (resolved via eng_find_symbol); seed=dirty blasts every symbol in the staging overlay ('what am I about to break with my current uncommitted edits?'); seed=diff blasts every symbol in files changed by a git diff (working tree vs HEAD by default, or pass ref_a+ref_b together for a ref range like main..HEAD)."

const DescSearchSemantic = "Natural-language search over embedded symbols (RRF-fused with FTS, lexical fallback when the embedder is offline). RESERVE this for true unknown-name / behavior-shaped queries ('where do we validate session tokens'). If you already know the identifier or an exact string, do NOT use this - use eng_find_symbol (exact + deterministic) or grep; semantic search is weaker and pricier on precise-logic queries. For 'what does this reach / who calls this' escalate to eng_get_call_chain / eng_get_blast_radius. Returns inline snippets so a follow-up Read is usually unnecessary. IMPORTANT - anti-spiral: if the response carries degraded_reason 'low_confidence' (the top hit landed in only one retriever, the precise-logic-miss signature), do NOT re-run the same query; switch tools (eng_find_symbol / grep for a known name) or rephrase substantially. Repeating a low-yield semantic query is the dominant cost failure. With repo_id omitted (and cwd outside any registered repo) the query fanned out across every registered repo in parallel and is fused with a single GLOBAL RRF so a top hit in one repo competes fairly with a top hit in another; each result then carries 'repo_id' so callers can disambiguate. The returned score is intra-query RRF (~0.01–0.03 typical range); use rank, not absolute score, to compare hits."

const DescDepsImportOnlyCaveat = "a module imported but only referenced via struct literals / type assertions (no resolved package-qualified call) will not appear yet"

const DescFindSymbolMatching = "Unqualified names also match - 'Run' finds Server.Run, Command.Run, etc., with exact matches first."

const DescContextPack = "Bundle a symbol's neighborhood (callers, callees, adjacent tests, recent commits, open findings, active task) into one token-bounded payload. Use at the START of a non-trivial change so you don't have to assemble surrounding context piecewise. Surfaces cross_repo_edges in both directions, so cross-repo callers/callees show up in the same response. Token budget: the full pack runs up to ~8k tokens; if you only need 'what does X directly call', pass scope=focused for the seed + direct callees alone (much cheaper). Reserve the default scope=full for genuine understand-before-edit moments, not narrow lookups."
