//go:build eval

package dbbench

import (
	"fmt"
	"math/rand"
)

// SeedConfig controls synthetic dataset size. The defaults model a small
// real repo (~10k LOC, modest edge fan-out, FTS rows for every node, an
// embedding row for every node).
type SeedConfig struct {
	Nodes       int
	EdgesPerSrc int
	RepoID      string
	Branch      string
	EmbedDim    int
	Seed        int64
}

// DefaultSeedConfig returns the bench's reproducible default.
func DefaultSeedConfig() SeedConfig {
	return SeedConfig{
		Nodes:       10000,
		EdgesPerSrc: 4,
		RepoID:      "bench-repo",
		Branch:      "main",
		EmbedDim:    768,
		Seed:        1,
	}
}

// SeedNode is one synthetic row generated by Generator.
type SeedNode struct {
	NodeID         string
	SymbolPath     string
	Name           string
	FilePath       string
	Kind           string
	Language       string
	ContentHash    string
	LineStart      int
	LineEnd        int
	LastPromotedAt int64
}

// SeedEdge is one synthetic edge generated by Generator.
type SeedEdge struct {
	EdgeID         string
	SrcNodeID      string
	DstNodeID      string
	Kind           string
	Confidence     string
	LastPromotedAt int64
}

// Generator produces deterministic synthetic data for a SeedConfig.
type Generator struct {
	cfg SeedConfig
	rng *rand.Rand
}

func NewGenerator(cfg SeedConfig) *Generator {
	return &Generator{cfg: cfg, rng: rand.New(rand.NewSource(cfg.Seed))}
}

var kinds = []string{"function", "method", "type", "var", "const"}

// Nodes yields every node row in order. Caller iterates and inserts.
func (g *Generator) Nodes(visit func(SeedNode) error) error {
	for i := 0; i < g.cfg.Nodes; i++ {
		file := fmt.Sprintf("pkg/mod%d/file%d.go", i/200, i/20)
		sym := fmt.Sprintf("pkg/mod%d.Func%d", i/200, i)
		name := fmt.Sprintf("Func%d", i)
		n := SeedNode{
			NodeID:         fmt.Sprintf("n%08d", i),
			SymbolPath:     sym,
			Name:           name,
			FilePath:       file,
			Kind:           kinds[i%len(kinds)],
			Language:       "go",
			ContentHash:    fmt.Sprintf("h%016x", g.rng.Uint64()),
			LineStart:      (i % 500) + 1,
			LineEnd:        (i % 500) + 5,
			LastPromotedAt: 1_700_000_000 + int64(i),
		}
		if err := visit(n); err != nil {
			return err
		}
	}
	return nil
}

// Edges yields synthetic intra-repo edges (caller-style: src→dst).
func (g *Generator) Edges(visit func(SeedEdge) error) error {
	total := g.cfg.Nodes * g.cfg.EdgesPerSrc
	for k := 0; k < total; k++ {
		src := k / g.cfg.EdgesPerSrc
		dst := g.rng.Intn(g.cfg.Nodes)
		e := SeedEdge{
			EdgeID:         fmt.Sprintf("e%010d", k),
			SrcNodeID:      fmt.Sprintf("n%08d", src),
			DstNodeID:      fmt.Sprintf("n%08d", dst),
			Kind:           "calls",
			Confidence:     "high",
			LastPromotedAt: 1_700_000_000 + int64(k),
		}
		if err := visit(e); err != nil {
			return err
		}
	}
	return nil
}

// EmbeddingBlob returns a deterministic float32-flavored blob of EmbedDim*4
// bytes. The bench measures blob scan cost; the contents don't matter.
func (g *Generator) EmbeddingBlob(seed int) []byte {
	buf := make([]byte, g.cfg.EmbedDim*4)
	r := rand.New(rand.NewSource(int64(seed) ^ g.cfg.Seed))
	for i := range buf {
		buf[i] = byte(r.Intn(256))
	}
	return buf
}

// QueueRowCount is how many synthetic queue rows the seeder enqueues.
// Smaller than node count: queue is a transient working set.
func QueueRowCount(cfg SeedConfig) int { return cfg.Nodes / 10 }
