// SPDX-License-Identifier: AGPL-3.0-only

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// gendocsCmd is a hidden command that renders the CLI command tree into a
// single Markdown reference page for the manual.
// It is hidden so it never appears in `veska --help`, and it walks its own
// root via cmd.Root so the output always tracks the real command set
// `make docs-gen` regenerates it and CI fails if the committed page drifts.
// We render Markdown ourselves rather than using cobra/doc's GenMarkdownTree
// because that emits one file per command with cross-file "SEE ALSO" links,
// which break under `mkdocs build --strict`. A single self-contained page with
// in-page anchors keeps the strict build green.
func gendocsCmd() *cobra.Command {
	return &cobra.Command{
		Use:           "gendocs <output-file>",
		Short:         "Generate the CLI reference Markdown (internal docs tooling)",
		Hidden:        true,
		Args:          cobra.ExactArgs(1),
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			out := args[0]
			var b strings.Builder
			renderCLIReference(cmd.Root(), &b)
			if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
				return err
			}
			return os.WriteFile(out, []byte(b.String()), 0o644)
		},
	}
}

// renderCLIReference writes a single Markdown page documenting root and all of
// its (non-hidden, non-help) subcommands, depth-first and alphabetised.
func renderCLIReference(root *cobra.Command, b *strings.Builder) {
	b.WriteString("# CLI reference\n\n")
	b.WriteString("<!-- GENERATED by `make docs-gen` (veska gendocs). DO NOT EDIT BY HAND. -->\n\n")
	b.WriteString("Every `veska` subcommand, generated from the command tree. ")
	b.WriteString("Run `veska <command> --help` for the same information at the terminal.\n")
	renderCommand(root, b)
}

func renderCommand(cmd *cobra.Command, b *strings.Builder) {
	if cmd.Hidden || cmd.IsAdditionalHelpTopicCommand() {
		return
	}

	path := cmd.CommandPath()
	depth := strings.Count(path, " ")
	// Root is an H2; nested commands deepen but cap at H4 so the table of
	// contents stays readable.
	level := min(depth+2, 4)

	fmt.Fprintf(b, "\n%s `%s`\n\n", strings.Repeat("#", level), path)

	if cmd.Short != "" {
		fmt.Fprintf(b, "%s\n\n", cmd.Short)
	}
	if cmd.Long != "" && cmd.Long != cmd.Short {
		fmt.Fprintf(b, "%s\n\n", cmd.Long)
	}

	if cmd.Runnable() {
		fmt.Fprintf(b, "```\n%s\n```\n\n", cmd.UseLine())
	}

	if ex := strings.TrimSpace(cmd.Example); ex != "" {
		b.WriteString("**Example:**\n\n```sh\n")
		b.WriteString(ex)
		b.WriteString("\n```\n\n")
	}

	if flags := strings.TrimRight(cmd.NonInheritedFlags().FlagUsages(), "\n"); flags != "" {
		b.WriteString("**Flags:**\n\n```\n")
		b.WriteString(flags)
		b.WriteString("\n```\n\n")
	}

	// Recurse into subcommands, alphabetised for a stable diff.
	children := cmd.Commands()
	sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })
	for _, c := range children {
		renderCommand(c, b)
	}
}
