package repo_test

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/whiskeyjimbo/veska/internal/infrastructure/repo"
)

// TestRepoIDForPath_MatchesAddForNormalPath verifies that the ID generated by RepoIDForPath equals the stored database ID.
func TestRepoIDForPath_MatchesAddForNormalPath(t *testing.T) {
	db := newTestDB(t)
	dir := newGitRepo(t)

	stored, _, err := repo.Add(context.Background(), db, dir)
	if err != nil {
		t.Fatalf("Add: %v", err)
	}
	if got := repo.RepoIDForPath(dir); got != stored {
		t.Errorf("RepoIDForPath(%q) = %q, want stored id %q", dir, got, stored)
	}
}

// TestRepoIDForPath_MatchesAddThroughSymlink verifies that RepoIDForPath resolves to the same ID when evaluated through a symlink.
func TestRepoIDForPath_MatchesAddThroughSymlink(t *testing.T) {
	db := newTestDB(t)
	realDir := newGitRepo(t)

	// Register the repository through the real path and retrieve it via the symlinked path.
	link := filepath.Join(t.TempDir(), "link-to-repo")
	if err := os.Symlink(realDir, link); err != nil {
		t.Skipf("symlinks unsupported on this platform: %v", err)
	}

	stored, _, err := repo.Add(context.Background(), db, realDir)
	if err != nil {
		t.Fatalf("Add: %v", err)
	}
	if got := repo.RepoIDForPath(link); got != stored {
		t.Errorf("RepoIDForPath(symlink %q) = %q, want stored id %q", link, got, stored)
	}
}
